export const cameras = [{
        name: 'Canon EOS R5',
        imgSrc: './images/EOSR5.png',
        imgAlt: 'Canon EOS R5 Mirror less',
        drawWeight: '123456',
        drawLength: '123456',
        massWeight: '25',
        speed: '20fps',
        resolution: '45 MP',
        level: 'advanced',
        category: 'professional',
        type: 'Full Frame',
        color: 'black',
        url: 'https://store.canon.es/canon-cuerpo-de-la-camara-mirrorless-eos-r5-de-canon/4147C025/',
    }, 
    {
        name: 'Canon EOS R5',
        imgSrc: './images/EOSR5.png',
        imgAlt: 'Canon EOS R5 Mirror less',
        drawWeight: '123456',
        drawLength: '123456',
        massWeight: '25',
        speed: '20fps',
        resolution: '45 MP',
        level: 'advanced',
        category: 'professional',
        type: 'DSLR',
        color: 'black',
        url: 'https://store.canon.es/canon-cuerpo-de-la-camara-mirrorless-eos-r5-de-canon/4147C025/',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        resolution: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        resolution: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        resolution: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  


];

// level - beginner int or advaced
// category - competition or hunting
// type - compound or recurve cameras
// {
//     name: '',
//     imgSrc: '',
//     imgAlt: '',
//     drawWeight: '',
//     drawLength: '',
//     massWeight: '',
//     speed: '',
//     resolution: '',
//     level: '',
//     category: '',
//     type: '',
//     color: '',
//     url: '',
// },