export const cameras = [{
        name: 'Canon EOS RP',
        imgSrc: './images/EOSR5.png',
        imgAlt: 'Canon EOS RP Mirrorless',
        massWeight: '485g',
        speed: '20 fps',
        axle2axle: '27MP',
        level: 'intermediate',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black, Tan, First Light Fusion',
        url: 'https://store.canon.es/canon-cuerpo-de-la-camara-mirrorless-eos-rp-de-canon/3380C195/',
    }, 
    {
        name: 'Canon EOS R5',
        imgSrc: './images/EOSR5.png',
        imgAlt: 'Canon EOS R5 Mirrorless',
        massWeight: '650g',
        speed: '20 fps',
        axle2axle: '45MP',
        level: 'advanced',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black, White',
        url: 'https://store.canon.es/canon-cuerpo-de-la-camara-mirrorless-eos-r5-de-canon/4147C025/',
    },  
    {
        name: 'Canon EOS 2000D',
        imgSrc: './images/EOS2000D.png',
        imgAlt: 'Canon EOS 2000D APSC',
        massWeight: '475g',
        speed: '3 fps',
        axle2axle: '24.1MP',
        level: 'beginner',
        category: 'hobby',
        type: 'dslr',
        color: 'Black',
        url: 'https://store.canon.es/canon-camara-canon-eos-2000d/2728C004/',
    },  
    {
        name: 'Nikon Z7',
        imgSrc: './images/NIKONZ7.png',
        imgAlt: 'Nikon Z7 Mirrorless',
        massWeight: '585g',
        speed: '9 fps',
        axle2axle: '45.7MP',
        level: 'advanced',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black',
        url: 'https://www.nikon.es/es_ES/product/digital-cameras/mirrorless/professional/z-7',
    },  
    {
        name: 'Nikon Z50',
        imgSrc: './images/NIKONZ50.png',
        imgAlt: 'Nikon Z50 Mirrorless',
        massWeight: '450g',
        speed: '11 fps',
        axle2axle: '20.9MP',
        level: 'intermediate',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black',
        url: 'https://www.nikon.es/es_ES/product/digital-cameras/mirrorless/enthusiast/z-50',
    },  
    {
        name: 'Nikon D7500',
        imgSrc: './images/NIKOND7500.png',
        imgAlt: 'Nikon D7500 DSLR',
        massWeight: '640g',
        speed: '8 fps',
        axle2axle: '20.9MP',
        level: 'beginner',
        category: 'hobby',
        type: 'dslr',
        color: 'Black',
        url: 'https://www.nikon.es/es_ES/product/digital-cameras/slr/consumer/d7500',
    }, 
    {
        name: 'Sony A7IV',
        imgSrc: './images/SONYA7IV.png',
        imgAlt: 'Sony A7IV Mirrorless',
        massWeight: '658g',
        speed: '10 fps',
        axle2axle: '33MP',
        level: 'advanced',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black',
        url: 'https://www.sony.es/electronics/camaras-lentes-intercambiables/ilce-7m4',
    }, 
    {
        name: 'Sony A7RIII',
        imgSrc: './images/SONYA7RIII.png',
        imgAlt: 'Sony A7RIII Mirrorless',
        massWeight: '450g',
        speed: '10 fps',
        axle2axle: '42.4MP',
        level: 'intermediate',
        category: 'professional',
        type: 'mirrorless',
        color: 'Black',
        url: 'https://www.sony.es/electronics/camaras-lentes-intercambiables/ilce-7rm3a',
    }, 
    {
        name: 'Sony A68',
        imgSrc: './images/SONYA68.png',
        imgAlt: 'Sony A68 DSLR',
        massWeight: '550g',
        speed: '8 fps',
        axle2axle: '24.2MP',
        level: 'beginner',
        category: 'hobby',
        type: 'dslr',
        color: 'Black',
        url: 'https://www.sony.es/electronics/camaras-lentes-intercambiables/ilca-68-body-kit',
    }, 


];

// level - beginner int or advaced
// category - professional or hobby
// type - mirrorless or recurve dslr
// {
//     name: '',
//     imgSrc: '',
//     imgAlt: '',
//     drawWeight: '',
//     drawLength: '',
//     massWeight: '',
//     speed: '',
//     axle2axle: '',
//     level: '',
//     category: '',
//     type: '',
//     color: '',
//     url: '',
// },